# Generated by Django 3.2.9 on 2021-11-07 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('death', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cases', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casesToday', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Today', models.DateField(default=datetime.date(2021, 11, 7))),
            ],
        ),
        migrations.CreateModel(
            name='overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('death', models.DecimalField(decimal_places=2, max_digits=10)),
                ('treating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cases', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avgCases7day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avgRecovered7day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avgDeath7day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.DecimalField(decimal_places=2, max_digits=10)),
                ('treating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cases', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovered', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death', models.DecimalField(decimal_places=2, max_digits=10)),
                ('treating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cases', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovered', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
