# Generated by Django 3.2.9 on 2021-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0002_alter_locations_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='today',
            name='Today',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='total',
            name='Today',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='casesToday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='avgCases7day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='avgDeath7day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='avgRecovered7day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overview',
            name='treating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='today',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='today',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='today',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='today',
            name='treating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='treating',
            field=models.IntegerField(default=0),
        ),
    ]
