# Generated by Django 3.2.9 on 2021-11-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0003_auto_20211108_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
