# Generated by Django 3.2.9 on 2021-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0004_alter_overview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='today',
            name='today_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='total',
            name='total_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
