# Generated by Django 3.2.9 on 2021-11-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0006_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='newss',
        ),
    ]
