# Generated by Django 3.2.9 on 2021-11-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0007_rename_news_newss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newss',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
