# Generated by Django 3.2.9 on 2021-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0009_auto_20211121_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
