# Generated by Django 3.2.9 on 2021-11-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapcovid', '0010_locations_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_huyen',
            name='id_huyen',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='covid_huyen',
            name='id_tinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinh', to='Mapcovid.locations'),
        ),
        migrations.CreateModel(
            name='Covid_xa',
            fields=[
                ('id_xa', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('cases', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('Today', models.DateField(auto_now=True)),
                ('id_huyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huyen', to='Mapcovid.covid_huyen')),
            ],
        ),
    ]
